version: "3"

networks:
  recipe-manager:

services:
  app:
    image: suhype/recipe-manager:${APP_VERSION}
    restart: unless-stopped
    environment:
      - CONTAINER_ROLE=app
    volumes:
      - html:/var/www/html
      - ./data:/var/www/html/storage/app
      - ./.env:/var/www/html/.env
    networks:
      - recipe-manager
    expose:
      - 80
    depends_on:
      - db
      - redis

  queue:
    image: suhype/recipe-manager:${APP_VERSION}
    restart: unless-stopped
    environment:
      - CONTAINER_ROLE=queue
    volumes:
      - html:/var/www/html
      - ./data:/var/www/html/storage/app
      - ./.env:/var/www/html/.env
    networks:
      - recipe-manager
    depends_on:
      - app

  scheduler:
    image: suhype/recipe-manager:${APP_VERSION}
    restart: unless-stopped
    environment:
      - CONTAINER_ROLE=scheduler
    volumes:
      - html:/var/www/html
      - ./data:/var/www/html/storage/app
      - ./.env:/var/www/html/.env
    networks:
      - recipe-manager
    depends_on:
      - app

  db:
    image: mariadb:${MARIADB_VERSION}
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
    networks:
      - recipe-manager
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    networks:
      - recipe-manager
    command: redis-server --requirepass ${REDIS_PASSWORD}
